version: '3.8'
services:
  mysql-container:
    image: mysql:latest
    environment:
      MYSQL_USER: crypolt
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3310:3310"
    networks:
      - my-network
    restart: always


  nodejs-container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    depends_on:
      - mysql-container
    networks:
      - my-network
    restart: always

networks:
  my-network:

